import type { Metadata } from "next";
import styles from "./page.module.css";

export const metadata: Metadata = {title:"AkashicOMNI | The Metadimensional Gateway",description:"The developing AkashicNET gateway: thirteen analytical perspectives, EXPAND squared and transparent outcome signals."};

const lenses=[
["01","AWAKEN","Awareness and awakening","Developing"],["02","HIERATIC","Symbols, archetypes and sacred meaning","Developing"],["03","HOMESENSE · Phase 8","Embodied life and synchronicity · TRANSCENDENCE active","Active"],["04","ADAPT","Learning through change","Developing"],["05","REGENERATE","Repair, renewal and flourishing","Exploratory"],["06","TRANSCEND","Transformation beyond present boundaries","Active Arts lens"],["07","#METAD v2.1","Compare models, contradictions and meaning","Versioned"],["08","ACTC v2.0","Agency, context, temporal order and candidate causes","Versioned"],["09","MultidimensionalCUT v4.0.0 · PAST","Prior patterns and inherited context","Versioned"],["10","MultidimensionalCUT v4.0.0 · PRESENT","Current conditions described precisely","Versioned"],["11","MultidimensionalCUT v4.0.0 · FUTURE","What to observe, test or cultivate next","Versioned"],["12","UMASC v7.2","Matter, awareness, systems and culture","Versioned"],["13","AkashicNET","Integrating synthesis without forced certainty","Developing"],
];
const signals=[["🩵","Resonance","A suggestive connection worth exploring"],["💛","Epiphany","A coherent insight surviving several lenses"],["💜","Revelation","A rare high-strength synthesis, still revisable"],["⚪","Unresolved","No conclusion is presently justified"],["🔴","Caution","Contradiction, weakness or potential harm"]];

export default function Page(){return <main className={styles.page}>
<header className={styles.nav}><a href="/">AKASHICNET.ORG</a><nav><a href="#lenses">13D perspectives</a><a href="#expand">EXPAND²</a><a href="/akashicone">AkashicONE</a></nav></header>
<section className={styles.imageHero}><img src="/images/akashicomni-metadimensional-gateway.webp" alt="AkashicOMNI: thirteen analytical perspectives arranged around a projected hypercube and toroidal heart inside the future AkashicONE Orb."/><div><p>MAIN METADIMENSIONAL GATEWAY · DEVELOPING · v0.1.0</p><h1>Akashic<span>OMNI</span></h1><h2>The boundless everything field.</h2><a href="#lenses">Explore thirteen perspectives ↓</a></div></section>
<section className={styles.intro}><p><strong>Multidimensional in analysis.</strong> <strong>Metadimensional in synthesis.</strong><br/>Scientific in inquiry. Brahmavihāra-guided in purpose.</p><small>Scientific, philosophical, contemplative and lived perspectives can meet without comparison becoming equivalence, confirmation or proof.</small></section>
<section className={styles.lenses} id="lenses"><p>THE AKASHICNET 13D ANALYTICAL STRUCTURE</p><h2>Thirteen ways of seeing.<br/>One living inquiry.</h2><ol>{lenses.map(([n,name,purpose,status])=><li key={n}><span>{n}</span><div><h3>{name}</h3><p>{purpose}</p><small>{status}</small></div></li>)}</ol><aside><strong>Evidence boundary:</strong> “13D” means thirteen analytical perspectives. The hypercube and orb are navigational metaphors, not proof of thirteen physical dimensions or a universal information field.</aside></section>
<section className={styles.expand} id="expand"><div><p>AKASHICOMNI v0.1.0</p><h2>EXPAND² v0.1</h2><article><b>PASS ONE · DISCERN</b><span>Question · Sources · Evidence labels · Assumptions · Missing information</span></article><article><b>PASS TWO · DEEPEN</b><span>Alternatives · Contradictions · Consequences · Time · Unknowns</span></article></div><div className={styles.signals}>{signals.map(([icon,name,text])=><article key={name}><i>{icon}</i><b>{name}</b><span>{text}</span></article>)}</div></section>
<section className={styles.destinations}><a href="/akashicvision"><b>AkashicVISION</b><span>Ethical compass →</span></a><a href="/akashictranscendence"><b>AkashicTRANSCENDENCE</b><span>Embodied Arts portal →</span></a><a href="/akashicone"><b>AkashicONE · The OMNI Orb</b><span>Future cosmic horizon →</span></a></section>
<footer><a href="/">AKASHICNET.ORG</a><span>OMNI sees the many · ONE remembers the whole</span></footer>
</main>}
