import type { Metadata } from "next";
import styles from "./prism.module.css";

export const metadata: Metadata = {
  title: "AkashicPRISM · From Wonder to Deeper Questions",
  description: "A proposed connection between AkashicPRISM, AkashicPSI and the Big Questions: preserve experience, examine explanations and let evidence refine understanding.",
};

const layers = [
  ["NET", "The living record", "Sources, stable identifiers, relationships and assessment history.", "/"],
  ["OMNI", "Many analytical perspectives", "Examine a question through complementary lenses, preserving their differences.", "/akashicomni"],
  ["PRISM", "The epistemic interface", "Distinguish experience, meaning, interpretation, evidence and uncertainty.", "/faq#prism-architecture"],
  ["PSI", "A proposed investigation stream", "Organise questions about reported anomalous perception and related experiences.", "#investigation"],
  ["BQ", "The larger questions", "Connect bounded findings to unresolved questions and better tests.", "/big-questions"],
] as const;
const steps = [
  ["01", "Record the experience", "What was reported? When was it recorded? Preserve the account, context and permission to use it."],
  ["02", "Examine the match", "Compare specific details against independent records. Include misses, ambiguities and the number of opportunities for a match."],
  ["03", "Trace information access", "Consider prior knowledge, ordinary sensory routes, chance, information leakage and later reconstruction."],
  ["04", "Distinguish explanations", "Choose observations or tests that could separate competing accounts. Record what would weaken each explanation."],
  ["05", "Contribute precisely", "State which claim is supported and how it affects a Big Question. Keep unresolved steps visible."],
] as const;
const questions = [
  ["Information", "Can information acquisition occur beyond recognised sensory routes?", "What conditions would exclude ordinary access and make the result independently checkable?"],
  ["Brain and experience", "How does a reported experience relate to measurable brain activity?", "What timing, measurements and limitations are needed before drawing an inference?"],
  ["Identity", "What would demonstrate continuity of an individual’s memory or identity?", "Which details distinguish personal continuity from other explanations?"],
  ["Discrimination", "Which observations could distinguish survival from competing explanations?", "Design a comparison in which the explanations make meaningfully different predictions."],
] as const;

export default function PrismQuestions() {
  return <main className={styles.page}>
    <nav className={styles.nav} aria-label="Page navigation"><a href="/">AKASHICNET</a><div><a href="#architecture">Architecture</a><a href="#investigation">Investigate</a><a href="#questions">Big Questions</a><a href="/faq">FAQ</a></div></nav>
    <header className={styles.hero}>
      <div className={styles.intro}><p className={styles.eyebrow}>AKASHICPRISM · DRAFT v0.1 · OMNI v0.5.0 PROPOSAL</p><h1>Keep the wonder.<br/><em>Deepen the question.</em></h1><p className={styles.lead}>From a meaningful experience to an inspectable record. From many possible explanations to a more precise question. A proposed meeting place for PRISM, AkashicPSI and the Big Questions.</p><a className={styles.button} href="#investigation">Follow an inquiry <span aria-hidden="true">↘</span></a></div>
      <figure className={styles.heroArt}><img src="/images/akashicprism-om-omega-v1.webp" width="2172" height="724" alt="Symbolic cosmic artwork: flowing rainbow light travels from OM through a golden-edged crystal prism and converges into a single luminous Omega point." fetchPriority="high"/><figcaption>Primordial OM → PRISM → a single Omega point. AI-generated artistic metaphor for exploration and focused inquiry; not a physical model or evidence of cosmic convergence.</figcaption></figure>
    </header>
    <section className={styles.section} id="architecture"><p className={styles.eyebrow}>01 / A CONNECTED ARCHITECTURE</p><h2>Different roles.<br/>A shared commitment to inquiry.</h2><p className={styles.prose}>AkashicNET contains the knowledge ecosystem. OMNI contributes analytical perspectives; PRISM connects their assessments with governed records. AkashicPSI is presented here as a proposed investigation stream. The Big Questions give individual findings a wider context.</p><div className={styles.layers}>{layers.map(([name,title,body,href])=><a className={styles.layer} key={name} href={href}><span>{name}</span><h3>{title}</h3><p>{body}</p><b aria-hidden="true">↗</b></a>)}</div><p className={styles.note}>PRISM is an epistemic interface layer. The proposed twelve OMNI perspectives include past, present and future views of CUT. This page introduces a design; it does not announce an implemented engine or a new release.</p></section>
    <section className={styles.band} id="investigation"><div className={styles.section}><p className={styles.eyebrow}>02 / FROM REPORT TO INVESTIGATION</p><h2>A remarkable report.<br/>Five careful questions.</h2><p className={styles.prose}>Hypothetical example: someone describes an event they say they could not ordinarily have known about. No real participant or study is represented below.</p><ol className={styles.steps}>{steps.map(([n,title,body])=><li key={n}><span className={styles.number}>{n}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol><aside className={styles.callout}><strong>Return whenever knowledge changes.</strong><p>New authorised material may strengthen, challenge or refine an assessment. Preserve earlier versions and explain the change. Evidence for anomalous perception would require a separate argument before supporting survival after death.</p></aside></div></section>
    <section className={styles.section} id="questions"><p className={styles.eyebrow}>03 / DEEPENING BQ001</p><div className={styles.questionHeading}><h2>Does consciousness continue<br/>beyond the individual?</h2><span className={styles.status}>UNRESOLVED</span></div><p className={styles.prose}>A broad question becomes more investigable when we separate its component claims. These are proposed subquestions, not newly registered Big Questions.</p><div className={styles.questions}>{questions.map(([name,q,next])=><article key={name}><span className={styles.eyebrow}>{name}</span><h3>{q}</h3><p>{next}</p></article>)}</div><a className={styles.textLink} href="/big-questions">Explore the Big Questions registry →</a></section>
    <section className={styles.band}><div className={styles.section}><p className={styles.eyebrow}>04 / MAKE EVERY CONNECTION TRACEABLE</p><h2>A finding can change<br/>the shape of a question.</h2><div className={styles.contributions} aria-label="Possible contributions to a Big Question">{["Supports", "Challenges", "Refines", "Contextualises", "Inconclusive"].map(x=><span key={x}>{x}</span>)}</div><div className={styles.record}><div><h3>Proposed BQ contribution record</h3><p>Link the precise claim and question to sources, supporting and conflicting observations, alternatives, uncertainty, the next discriminating test and revision history.</p></div><div><h3>Acceptance can evolve</h3><p>A specific claim can become well-supported when suitable evidence warrants it. Acceptance remains scoped, reviewed and revisable. Registering a blocked record keeps the question available; it does not count as a completed read or verified conclusion.</p></div></div><p className={styles.note}>Database first: each larger connection should lead back to an inspectable record. Repeated citations of the same underlying work are not independent corroboration. Publication and reuse permissions require separate review.</p></div></section>
    <section className={styles.section}><p className={styles.eyebrow}>05 / MEANING BELONGS IN THE RECORD</p><h2>Experience deserves care.<br/>Explanation deserves examination.</h2><p className={styles.prose}>An experience may transform someone’s sense of identity, compassion or relationship with Pachamama. Those consequences deserve careful inquiry while its external cause remains uncertain. Spiritual, philosophical and scientific interpretations can coexist as attributed perspectives.</p><p className={styles.prose}>Comparisons with living traditions must preserve their language, context, community authority and sharing restrictions. Similar descriptions do not establish a shared cause or make distinct traditions interchangeable.</p><blockquote>More understanding can mean a sharper question,<br/>even before it means an answer.</blockquote><div className={styles.actions}><a className={styles.button} href="/insights/akashicprism-plug-and-play-consciousness">Explore the inquiry jigsaw →</a><a className={styles.textLink} href="mailto:support@akashicnet.org?subject=PRISM%20Big%20Questions%20feedback">Suggest a source or a better question →</a></div></section>
    <footer className={styles.footer}><p>Original vision and editorial direction: the AkashicNET founder.<br/>Developed and formalised through human–AI collaboration.</p><p>Draft prepared 23 September 2026 · Conceptual proposal · Approximately 5 minutes</p><p>BQ001 remains UNRESOLVED. Existing privacy, cultural authority, rights, evidence and publication boundaries apply.</p><a href="/">Keep the wonder · Follow the evidence · Serve life</a></footer>
  </main>;
}
