#!/usr/bin/env python3
"""Validate typed status and deterministic renderings, not free-form semantics."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = "website/data/public-status.json"
MANIFEST = "manifests/v0.16-release-candidate.json"
EXPECTED = {'schema_version': 1, 'product_stage': 'PUBLIC_BETA', 'sealed_baseline': {'version': 'v0.15', 'status': 'SEALED_BASELINE'}, 'candidate': {'version': 'v0.16.0-beta.2', 'status': 'GOVERNED_CANDIDATE', 'sealed': False}, 'site_checkpoint': {'version': 'v0.16.7', 'status': 'SITE_CHECKPOINT', 'is_release': False}, 'target': {'version': 'v0.17.0', 'status': 'NEXT_MINOR', 'released': False}, 'bq001': {'status': 'UNRESOLVED', 'accepted_edges': 0}, 'reddit_live_access': 'HOLD', 'promotion_allowed': False}
SURFACES = {
    "website/app/page.tsx": ("website/status-templates/home.tsx.in", {"CURRENT_LABEL"}),
    "website/app/development-progress/page.tsx": (
        "website/status-templates/progress.tsx.in",
        {"CHECKPOINT_ROWS", "PROGRESS_INTRO", "BQ001_BOUNDARY"}),
}
HEADER = "// Generated by scripts/validate_public_status_consistency_v016.py --write. Edit the status templates.\n"

def unique_pairs(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate JSON key: " + key)
        result[key] = value
    return result

def read_json(path):
    def invalid(value):
        raise ValueError("non-finite JSON value: " + value)
    return json.loads(path.read_text(), object_pairs_hook=unique_pairs, parse_constant=invalid)

def validate_data(data, manifest):
    # Canonical JSON comparison also distinguishes booleans from integer values.
    if json.dumps(data, sort_keys=True) != json.dumps(EXPECTED, sort_keys=True):
        raise ValueError("public status contract drift (unknown fields, types or values)")
    if manifest.get("schema_version") != data["candidate"]["version"].removeprefix("v"):
        raise ValueError("candidate version disagrees with governed manifest")
    if manifest.get("artifact_status") != "UNRELEASED_REVIEW_CANDIDATE":
        raise ValueError("governed candidate must remain unreleased")
    summary = manifest.get("candidate_summary", {})
    if summary.get("question_id") != "BQ001" or summary.get("question_status") != "UNRESOLVED" or type(summary.get("accepted_edge_count")) is not int or summary["accepted_edge_count"] != 0:
        raise ValueError("governed BQ001 boundaries drift")
    guards = manifest.get("promotion_boundaries", {})
    if set(guards) != {"truth", "scientific_evidence", "rights", "identity", "safety_efficacy", "private_data", "edge_acceptance", "website_publication"} or any(value is not False for value in guards.values()):
        raise ValueError("governed promotion boundaries must remain closed")

def fragments(data):
    baseline = data["sealed_baseline"]["version"]
    candidate = data["candidate"]["version"]
    checkpoint = data["site_checkpoint"]["version"]
    target = data["target"]["version"]
    rows = 'const checkpoints = [\n  ["{baseline}", "SEALED BASELINE", "Public Sync & Observability Beta. Immutable release evidence remains governed by its exact commit and manifest."],\n  ["{candidate}", "GOVERNED CANDIDATE", "The second prerelease candidate, registered in the governed release-candidate manifest. Validation and exact-head review remain required; this is not a sealed release."],\n  ["{checkpoint}", "SITE CHECKPOINT", "A presentation and integration marker. It is not a release, a percentage, or a claim that seven formal patch releases occurred."],\n  ["{target}", "NEXT MINOR", "Reached only after intended scope, executable exact-head checks, review closure and release-integrity verification."],\n];'
    for name, value in (("baseline", baseline), ("candidate", candidate), ("checkpoint", checkpoint), ("target", target)):
        rows = rows.replace("{" + name + "}", value)
    intro = 'AkashicNET distinguishes an immutable sealed release from an active development checkpoint. The governed candidate is <strong style={{ color: "#f1d47b" }}>@candidate@</strong>. The separate <strong style={{ color: "#f1d47b" }}>@checkpoint@ site checkpoint</strong> records presentation and integration progress toward @target@.'
    for name, value in (("candidate", candidate), ("checkpoint", checkpoint), ("target", target)):
        intro = intro.replace("@" + name + "@", value)
    return {
        "CURRENT_LABEL": f"Public Beta · {baseline} sealed · {candidate} governed candidate",
        "CHECKPOINT_ROWS": rows,
        "PROGRESS_INTRO": intro,
        "BQ001_BOUNDARY": "BQ001 remains " + data["bq001"]["status"] + "; no testimony, hypothesis or inference is silently promoted to established evidence.",
    }

def render(root=ROOT):
    data = read_json(root / DATA)
    validate_data(data, read_json(root / MANIFEST))
    values = fragments(data)
    outputs = {}
    for output, (source, required) in SURFACES.items():
        text = (root / source).read_text()
        for token in required:
            marker = "@@" + token + "@@"
            if text.count(marker) != 1:
                raise ValueError("required status slot missing or duplicated: " + token)
            text = text.replace(marker, values[token])
        if "@@" in text:
            raise ValueError("unknown template slot")
        outputs[output] = HEADER + text
    return outputs

def check(root=ROOT, write=False):
    outputs = render(root)
    for path, expected in outputs.items():
        target = root / path
        if write:
            target.write_text(expected)
        elif not target.is_file() or target.read_text() != expected:
            raise ValueError("generated public status surface drift: " + path)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate governed public surfaces")
    args = parser.parse_args()
    try:
        check(write=args.write)
    except (ValueError, OSError, TypeError, KeyError) as error:
        raise SystemExit("FAIL: " + str(error))
    print("PASS: typed public status and generated surfaces agree; free-form prose requires editorial review")

if __name__ == "__main__":
    main()
