#!/usr/bin/env python3
"""Validate the pinned PRISM metadata-only crosswalk, without network access.

This is a checkpoint contract, not a future DOI adjudication schema. A verified
source read or any other state transition requires a separately reviewed update.
IDs were reconciled against the BLOCKED records in the immutable ledger below;
they are explicit because base36 IDs must not be generated by numeric arithmetic.
"""
import argparse
import json
from pathlib import Path

DEFAULT_PATH = Path(__file__).resolve().parents[1] / "references/knowledge-governance/prism-n2n-blocked-admission-crosswalk-v0.1.json"

EXPECTED_IDS = ['10001c',
 '10001d',
 '10001e',
 '10001f',
 '100020',
 '100021',
 '100022',
 '100023',
 '100024',
 '100025',
 '100026',
 '100027',
 '100028',
 '100029',
 '10002a',
 '10002b',
 '10002c',
 '10002d',
 '10002e',
 '10002f',
 '100030',
 '100031',
 '100032',
 '100033',
 '100034',
 '100035',
 '100036',
 '100037',
 '100038',
 '100039',
 '10003a',
 '10003b',
 '10003c',
 '10003d',
 '10003e',
 '10003f',
 '100040',
 '100041',
 '100042',
 '100043',
 '100044']

SOURCE_CHECKPOINT = {'repository': 'tws9stmcbf-web/AkashicNET',
 'pull_request': 377,
 'branch': 'docs/n2n-analysis-ledger-20260922',
 'head_commit': 'd852f14f3c4f35c96460e5112878c1ffe4ffffa5',
 'path': 'references/community/n2n-analysis-ledger.json',
 'blob_sha': '6e124881f9a95fa3a255f72324b08a4d63ef59a6',
 'ledger_checkpoint': {'complete_in_this_ledger': 0,
                       'blocked': 41,
                       'next_pending_post_id': '100045',
                       'next_action': 'Continue pending repository-only assessment. '
                                      'Keep PR #378 substantive-reading counts '
                                      'separate.'}}

METADATA_CHECK = {'source_path': 'references/community/n2n-pilot-index.csv',
 'source_commit': 'd852f14f3c4f35c96460e5112878c1ffe4ffffa5',
 'source_blob': '20ef9b76ab327b996a0959856c5fa1d5e7acb0e4',
 'matched_unique_post_ids': 41,
 'doi_strings_found': 0,
 'separate_external_source_links': 0,
 'external_source_fields_repeating_post_url': 41}

SAFEGUARDS = {'reddit_live_access': 'HOLD',
 'source_bodies_committed': False,
 'comments_or_usernames_committed': False,
 'evidence_promotion': False,
 'rights_promotion': False,
 'accepted_canonical_edges': 0,
 'big_questions': 'UNRESOLVED',
 'website_integration': 'HOLD',
 'publication': 'HOLD'}

RECORD_BOUNDARY = {'source_ledger_status': 'BLOCKED',
 'source_analysis_complete': False,
 'prism_registration_status': 'PRISM_REGISTERED_METADATA_ONLY',
 'prism_investigation_status': 'evidence_needed',
 'admissible_scope': ['stable_repository_identifier',
                      'repository_metadata_provenance',
                      'blocker_and_next_action',
                      'shared_investigation_linkage'],
 'interpretive_modes_assigned': [],
 'evidence_lane_assignment': 'NOT_ASSIGNED_SOURCE_CONTENT_UNREAD',
 'cultural_authority_status': 'NOT_ASSESSED_SOURCE_CONTENT_UNREAD',
 'rights_state': 'METADATA_LINK_ONLY_NO_REPRODUCTION',
 'privacy_state': 'METADATA_ONLY_NO_SOURCE_BODIES_COMMENTS_OR_USERNAMES',
 'promotion_permissions': {'substantive_interpretation': False,
                           'scientific_evidence': False,
                           'rights': False,
                           'accepted_canonical_edge': False,
                           'website_integration': False,
                           'publication': False}}

UNREAD_RESOLUTION = {'status': 'NOT_YET_CHECKED',
 'primary_doi': None,
 'additional_dois': [],
 'paper_title': None,
 'paper_authors': [],
 'relationship_to_post': 'UNVERIFIED',
 'link_found_in': None,
 'link_evidence_locator': None,
 'verification_depth': 'NONE',
 'checked_on': None}

COUNTER_EFFECT = {'new_records': 0,
 'new_post_reads': 0,
 'verified_doi_assignments': 0,
 'completed_comparisons': 0,
                  'evidence_promotions': 0}


def same(actual, expected):
    """Require JSON types too: false must never pass as the integer zero."""
    if type(actual) is not type(expected):
        return False
    if isinstance(expected, dict):
        return actual.keys() == expected.keys() and all(
            same(actual[k], v) for k, v in expected.items())
    if isinstance(expected, list):
        return len(actual) == len(expected) and all(
            same(a, b) for a, b in zip(actual, expected))
    return actual == expected


def validate(data):
    errors = []

    def require(condition, message):
        if not condition:
            errors.append(message)

    def fixed(obj, key, expected, where):
        require(isinstance(obj, dict) and key in obj and same(obj[key], expected),
                f'{where}.{key}: violates pinned metadata-only contract')

    if not isinstance(data, dict):
        return ['crosswalk: expected object']
    fixed(data, 'source_checkpoint', SOURCE_CHECKPOINT, 'crosswalk')
    fixed(data, 'safeguards', SAFEGUARDS, 'crosswalk')
    follow = data.get('doi_enrichment_followup')
    fixed(follow, 'metadata_check', METADATA_CHECK, 'doi_enrichment_followup')
    fixed(follow, 'counter_effect', COUNTER_EFFECT, 'doi_enrichment_followup')
    records = data.get('records')
    if not isinstance(records, list):
        return errors + ['records: expected array']
    ids = []
    for index, record in enumerate(records):
        where = f'records[{index}]'
        if not isinstance(record, dict):
            errors.append(f'{where}: expected object')
            continue
        subject = record.get('subject_ref')
        if (not isinstance(subject, dict)
                or set(subject) != {'subject_id', 'subject_type'}
                or not isinstance(subject.get('subject_id'), str)):
            errors.append(f'{where}.subject_ref: expected stable community-post ID')
        else:
            ids.append(subject['subject_id'])
            fixed(subject, 'subject_type', 'community_post', where + '.subject_ref')
        for key, expected in RECORD_BOUNDARY.items():
            fixed(record, key, expected, where)
        resolution = record.get('paper_link_resolution')
        require(isinstance(resolution, dict) and
                set(resolution) == set(UNREAD_RESOLUTION) | {'note'},
                f'{where}.paper_link_resolution: missing or unknown fields')
        for key, expected in UNREAD_RESOLUTION.items():
            fixed(resolution, key, expected, where + '.paper_link_resolution')
        require(isinstance(resolution, dict) and
                isinstance(resolution.get('note'), str) and bool(resolution['note'].strip()),
                f'{where}.paper_link_resolution.note: expected nonempty explanation')
    require(len(ids) == len(EXPECTED_IDS) and sorted(ids) == sorted(EXPECTED_IDS),
            'records: stable IDs must match the 41 pinned BLOCKED records exactly once')
    summary = data.get('assessment_summary')
    # Counts are computed from actual record dispositions, then constrained by
    # the pinned membership and per-record boundary checks above.
    mappings = {
        'original_blocked': ('source_ledger_status', 'BLOCKED'),
        'original_complete': ('source_analysis_complete', True),
        'prism_registered_metadata_only': ('prism_registration_status', 'PRISM_REGISTERED_METADATA_ONLY'),
    }
    fixed(summary, 'source_records', len(records), 'assessment_summary')
    for key, (field, value) in mappings.items():
        count = sum(isinstance(r, dict) and same(r.get(field), value) for r in records)
        fixed(summary, key, count, 'assessment_summary')
    for key, permission in {
        'substantive_interpretation_eligible': 'substantive_interpretation',
        'scientific_evidence_promotion_eligible': 'scientific_evidence',
        'canonical_edge_eligible': 'accepted_canonical_edge',
        'publication_eligible': 'publication',
    }.items():
        count = sum(isinstance(r, dict) and isinstance(r.get('promotion_permissions'), dict)
                    and r['promotion_permissions'].get(permission) is True for r in records)
        fixed(summary, key, count, 'assessment_summary')
    return errors


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f'duplicate JSON key: {key}')
        result[key] = value
    return result


def load_crosswalk(path):
    def reject_constant(value):
        raise ValueError(f'non-JSON constant: {value}')
    return json.loads(path.read_text(encoding='utf-8'), object_pairs_hook=unique_object,
                      parse_constant=reject_constant)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('path', nargs='?', type=Path, default=DEFAULT_PATH)
    args = parser.parse_args()
    try:
        errors = validate(load_crosswalk(args.path))
    except (OSError, ValueError) as exc:
        errors = [str(exc)]
    if errors:
        for error in errors:
            print(f'ERROR: {error}')
        return 1
    print('PASS: 41 pinned metadata-only records; DOI resolution unchecked; HOLD intact')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
